language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
addons:
  artifacts:
    s3_region: sa-east-1
    bucket: idg
    permissions: public-read
    paths:
    - $(find parts/test -type f | tr "\n" ":")
addons:
  # XXX: use an older Firefox ESR as we are stuck with selenium = 2.53.5
  #      https://github.com/SeleniumHQ/selenium/issues/2739#issuecomment-249482533
  firefox: 45.9.0esr
env:
  global:
  - PLONE_CSRF_DISABLED=true
  matrix:
  # TODO: update https://github.com/plonegovbr/portalpadrao.release/blob/master/README.md
  - DEVELOPMENT=true
  - PRODUCTION=true
matrix:
  allow_failures:
  - env: PRODUCTION=true
  fast_finish: true
before_install:
- test $DEVELOPMENT && cp travis-development.cfg buildout.cfg || cp travis-production.cfg buildout.cfg
# FIXME: I have no idea how and why six==1.11.0 is being installed
- pip uninstall -y six
install:
- pip install -U setuptools==36.6.1
- python bootstrap.py
- bin/buildout annotate
- bin/buildout
# O release 1.1.5.1 veio com um erro e não vinha com os eggs do brasil.gov.portal.
# Dessa forma, passamos a testar se o egg foi realmente adicionado no buildout
# para que esse erro não ocorra novamente.
# Caso altere a versão do zc.buildout, pode ser que você necessite alterar o
# arquivo onde procura a string, trocando bin/instance por parts/instance.site.py
# por exemplo.
- grep -q 'brasil.gov.portal' bin/instance
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
# FIXME: we have isolation issues running tests
- bin/test -s brasil.gov.agenda
- bin/test -s brasil.gov.barra
- bin/test -s brasil.gov.portal
- bin/test -s brasil.gov.portlets
- bin/test -s brasil.gov.temas
- bin/test -s brasil.gov.tiles
- bin/test -s brasil.gov.vcge
after_failure:
- grep brasil.gov bin/test
notifications:
  irc: irc.freenode.org#plonegovbr
